name: Build ArduPilot ESP32S3

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  plane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt-get install -y python3-pip git
      - name: Get ESP32S3 Toolchain (Linux)
        run: |
          git clone https://github.com/TangMeng12/prebuilts_gcc_linux-x86_64_xtensa-esp32s3-elf.git
          echo "$PWD/prebuilts_gcc_linux-x86_64_xtensa-esp32s3-elf/bin" >> $GITHUB_PATH
      - name: Verify toolchain
        run: |
          which xtensa-esp32s3-elf-ar
          xtensa-esp32s3-elf-ar --version

      - name: Add toolchain to PATH
        run: echo "$PWD/toolchain-xtensa-esp32s3/bin" >> $GITHUB_PATH

      - name: Verify toolchain
        run: |
          which xtensa-esp32s3-elf-ar
          xtensa-esp32s3-elf-ar --version

      - run: |
          python3 waf configure --board esp32s3devkit
          python3 waf plane
      - uses: actions/upload-artifact@v4
        with:
          name: plane-esp32s3n16r8
          path: build/esp32s3n16r8/bin/*

  copter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt-get install -y python3-pip git
      - name: Get ESP32S3 Toolchain
        run: |
          git clone https://github.com/kubilaykerti/toolchain-xtensa-esp32s3.git
          echo "$PWD/toolchain-xtensa-esp32s3/bin" >> $GITHUB_PATH

      - name: Verify toolchain
        run: |
          which xtensa-esp32s3-elf-ar
          xtensa-esp32s3-elf-ar --version
      - run: |
          python3 waf configure --board esp32s3devkit
          python3 waf copter
      - uses: actions/upload-artifact@v4
        with:
          name: copter-esp32s3n16r8
          path: build/esp32s3n16r8/bin/*

  rover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt-get install -y python3-pip git
      - name: Get ESP32S3 Toolchain
        run: |
          git clone https://github.com/kubilaykerti/toolchain-xtensa-esp32s3.git
          echo "$PWD/toolchain-xtensa-esp32s3/bin" >> $GITHUB_PATH

      - name: Verify toolchain
        run: |
          which xtensa-esp32s3-elf-ar
          xtensa-esp32s3-elf-ar --version
      - run: |
          python3 waf configure --board esp32s3devkit
          python3 waf rover
      - uses: actions/upload-artifact@v4
        with:
          name: rover-esp32s3n16r8
          path: build/esp32s3n16r8/bin/*
